steps:
  # 1. Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/weihsien-wang-portfolio/portfolio-repo/portfolio:$COMMIT_SHA",
        ".",
      ]

  # 2. Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/weihsien-wang-portfolio/portfolio-repo/portfolio:$COMMIT_SHA",
      ]

  # 3. Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "portfolio-site"
      - "--image"
      - "us-central1-docker.pkg.dev/weihsien-wang-portfolio/portfolio-repo/portfolio:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--allow-unauthenticated"

# Store the image reference for traceability
images:
  - "us-central1-docker.pkg.dev/weihsien-wang-portfolio/portfolio-repo/portfolio:$COMMIT_SHA"
